#!/bin/bash

# HW2 Quick Start Script
# This script provides instructions for running HW2 simulation

echo "═══════════════════════════════════════════════════════════"
echo "  HW2 - Sensor Integration & Visualization"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "IMPORTANT: Open 3-4 separate terminals and run these commands:"
echo ""
echo "─────────────────────────────────────────────────────────"
echo "TERMINAL 1: Launch Gazebo (without RViz to avoid libpthread error)"
echo "─────────────────────────────────────────────────────────"
echo "cd ~/Documents/GitHub/hws_repo"
echo "source /opt/ros/humble/setup.bash"
echo "source install/setup.bash"
echo "ros2 launch robot_hw1 hw2.launch.py use_rviz:=false"
echo ""
echo "Wait 10 seconds for Gazebo to fully load!"
echo ""
echo "─────────────────────────────────────────────────────────"
echo "TERMINAL 2: Start Robot Motion (Circular Trajectory)"
echo "─────────────────────────────────────────────────────────"
echo "cd ~/Documents/GitHub/hws_repo"
echo "source /opt/ros/humble/setup.bash"
echo "source install/setup.bash"
echo "ros2 run robot_hw1 cmd_vel_publisher"
echo ""
echo "You should see the robot moving in circles!"
echo ""
echo "─────────────────────────────────────────────────────────"
echo "TERMINAL 3: Launch RViz (Manually to avoid libpthread bug)"
echo "─────────────────────────────────────────────────────────"
echo "cd ~/Documents/GitHub/hws_repo"
echo "source /opt/ros/humble/setup.bash"
echo "source install/setup.bash"
echo "rviz2 -d install/robot_hw1/share/robot_hw1/rviz/hw2_config.rviz"
echo ""
echo "If RViz still crashes, try:"
echo "sudo snap remove rviz2  # Remove snap version"
echo "sudo apt install ros-humble-rviz2  # Install apt version"
echo ""
echo "─────────────────────────────────────────────────────────"
echo "TERMINAL 4 (OPTIONAL): IMU Data Visualization"
echo "─────────────────────────────────────────────────────────"
echo "cd ~/Documents/GitHub/hws_repo"
echo "source /opt/ros/humble/setup.bash"
echo "source install/setup.bash"
echo "rqt_multiplot"
echo ""
echo "In rqt_multiplot GUI:"
echo "  File → Open → install/robot_hw1/share/robot_hw1/config/imu_multiplot.xml"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Quick Checks"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Check if sensors are publishing:"
echo "  ros2 topic list"
echo "  ros2 topic echo /camera/rgbd_camera/image_raw --once"
echo "  ros2 topic echo /imu/data --once"
echo ""
echo "Check robot is moving:"
echo "  ros2 topic echo /cmd_vel"
echo "  ros2 topic echo /odom"
echo ""
echo "═══════════════════════════════════════════════════════════"
